coingaming/moon-design

.circleci/config.yml
=> feat(ci): .circleci/config.yml

packages/table/src/Table.tsx
=> feat: add expandedByDefault prop

packages/components/src/snackbar/Snackbar.tsx
=> feat: snackbar custom background color

packages/components/src/snackbar/Snackbar.tsx
=> feat: snackbar custom background color (#1264)

next-docs/pages/getting-started.tsx
=> feat: trigger build

packages/themes/src/luckyslotsDark/luckyslotsDark.ts, packages/themes/src/luckyslotsLight/luckyslotsLight.ts
=> feat: luckyslotsDark & luckyslotsLight themes

packages/themes/src/luckyslotsDark/luckyslotsDark.ts, packages/themes/src/luckyslotsLight/luckyslotsLight.ts
=> feat: luckyslotsDark & luckyslotsLight themes (#1281)

packages/themes/src/luckyslotsDark/luckyslotsDark.ts, packages/themes/src/luckyslotsLight/luckyslotsLight.ts
=> fix: update luckyslots colours

next-docs/components/Layout.tsx, next-docs/components/facing/Future.tsx, next-docs/styles/custom.css
=> Fix future block width for mobiles

next-docs/components/CodeSnippet.tsx
=> fix: code snippet overflow

next-docs/components/CodeSnippet.tsx
=> fix: code snippet overflow (#1294)

next-docs/pages/getting-started.tsx
=> fix: getting-started.tsx peer deps

next-docs/pages/getting-started.tsx
=> fix: getting-started.tsx peer deps (#1296)

next-docs/pages/components/search.tsx
=> fix: search component preview

CHANGELOG.md, lerna.json, next-docs/CHANGELOG.md, packages/accordion/CHANGELOG.md, packages/assets/CHANGELOG.md, packages/calendar/CHANGELOG.md, packages/charts/CHANGELOG.md, packages/components/CHANGELOG.md, packages/core/CHANGELOG.md, packages/core/src/search/Search.tsx, packages/core/src/search/private/components/Input.ts, packages/core/src/search/private/components/Popup.tsx, packages/core/src/search/private/components/SearchResults.tsx, packages/core/src/search/private/components/Styles.ts, packages/draggabletable/CHANGELOG.md, packages/global/CHANGELOG.md, packages/notifications/CHANGELOG.md, packages/pagination/CHANGELOG.md, packages/popover/CHANGELOG.md, packages/sidebar/CHANGELOG.md, packages/table/CHANGELOG.md, packages/themes/CHANGELOG.md, packages/utils/CHANGELOG.md
* feature/B1M2-2919 base component for moon-core search
* fix: improve search styles
* fix: cleanup code
* delete: search core.tsx
* fix: navigation route
=> Feature/b1 m2 2919 search component fixes (#1306)

next-docs/pages/components/search.tsx, packages/core/src/search/Search.tsx, packages/core/src/search/private/components/Input.ts, packages/core/src/search/private/components/SearchResults.tsx, packages/core/src/search/private/components/Styles.ts
* fix: B1M2-2919 update border on dark theme
* fix: B1M2-2919 styling fixes
* fix: B1M2-2919 search results accepts any component
=> Feature/b1-m2-2919 (#1310)

packages/assets/src/groupIcons/GroupIconCurrency.tsx, packages/assets/src/icons/IconCurrencyDoge.tsx
=> feat: add DOGE icon (#1313)

CHANGELOG.md, lerna.json, next-docs/CHANGELOG.md, next-docs/components/themes/BrandThemeSelector.tsx, packages/accordion/CHANGELOG.md, packages/assets/CHANGELOG.md, packages/calendar/CHANGELOG.md, packages/charts/CHANGELOG.md, packages/components/CHANGELOG.md, packages/core/CHANGELOG.md, packages/draggabletable/CHANGELOG.md, packages/global/CHANGELOG.md, packages/notifications/CHANGELOG.md, packages/pagination/CHANGELOG.md, packages/popover/CHANGELOG.md, packages/sidebar/CHANGELOG.md, packages/table/CHANGELOG.md, packages/themes/CHANGELOG.md, packages/utils/CHANGELOG.md, yarn.lock
=> fix: remove lodash from nextjs app (#1324)

next-docs/pages/icons.tsx
=> fix: icons page, trigger build

.circleci/config.yml
=> fix(ci): publish for build_docs_and_push

next-docs/pages/components/search.tsx, packages/core/src/search/Search.tsx
* fix: B1M2-2163 styling fixes for search component in mobile
* fix: export SearcProps
* fix: Use default values
=> Feature/search updates - export search props and other fixes (#1337)

packages/assets/src/logos/LogoBetaddaFull.tsx
=> fix: fix default prop

packages/assets/src/logos/LogoBetaddaFull.tsx
=> fix: fix default prop (#1342)

next-docs/pages/components/search.tsx, packages/core/src/search/Readme.mdx, packages/core/src/search/Search.tsx, packages/core/src/search/private/components/Input.ts, packages/core/src/search/private/components/Popup.tsx, packages/core/src/search/private/components/Styles.ts
Fix browsing search results with TAB key
Rewrite - close search popup when focus moves outside the search popup
=> fix: focus outside will close popup (even when using TAB)

next-docs/pages/components/search.tsx, packages/core/src/search/Readme.mdx, packages/core/src/search/Search.tsx, packages/core/src/search/private/components/Input.ts, packages/core/src/search/private/components/Popup.tsx, packages/core/src/search/private/components/Styles.ts
* fix: focus outside will close popup (even when using TAB)
* fix: Clear icon focus color
* fix: remove console log
* fix: remove console log
* fix: search, more cleanup
=> release-fix_for_search

packages/core/src/search/Search.tsx
* fix: B1M2-3620 add keyboard navigation to search
* fix: B1M2-3620 noValidate to search form
=> feat: b1 m2 3620 add keyboard navigation to search (#1358)

packages/assets/.config/templates/svgr.template.js, packages/assets/src/logos/LogoBetaddaFull.tsx
=> fix: fix betadda logo color

packages/assets/.config/templates/svgr.template.js, packages/assets/src/logos/LogoBetaddaFull.tsx
=> release betadda logo color

next-docs/pages/components/draggabletable.tsx
=> fix: type for draggabletable page

next-docs/package.json, next-docs/pages/components/draggabletable.tsx
=> fix: added moon-draggabletable to package

next-docs/package.json, next-docs/pages/components/draggabletable.tsx, packages/draggabletable/src/DraggableTable.tsx
DraggableTable: use row object in onDropRow event (#1362)
=> Release-fix-for-draggabletable

next-docs/pages/components/list-item.tsx, packages/core/src/index.ts, packages/core/src/listItem/ListItem.tsx
=> feat: addd ListItem component [B1M2-3510]

next-docs/package.json, next-docs/pages/components/list-item.tsx, yarn.lock
=> fix: add list-item component [B1M2-3510]

packages/core/src/search/Search.tsx
=> fix:B1M2-3695 sportsbet-packages compiling issue (#1380)

packages/core/src/search/Search.tsx, packages/core/src/search/private/components/Styles.ts
* fix:B1M2-3695 fix search doesn't close in mobile
* fix:B1M2-3695 isOpen prop
=> B1M2-3695 close search (#1386)

packages/core/src/search/Search.tsx
* fix:B1M2-3695 isOpen as optional prop
* fix:B1M2-3695 fix build error
=> fix:B1M2-3695 isOpen as an optional prop (#1388)

packages/core/src/search/Search.tsx
Add onFocus and onBlur event from outside
=> fix:B1M2-3695 add onBlur and onFocus events

packages/core/src/search/Search.tsx
=> fix:B1M2-3695 add onBlur and onFocus events (#1392)

CHANGELOG.md, next-docs/CHANGELOG.md, next-docs/pages/components/avatar.tsx, packages/accordion/CHANGELOG.md, packages/assets/CHANGELOG.md, packages/calendar/CHANGELOG.md, packages/charts/CHANGELOG.md, packages/components/CHANGELOG.md, packages/components/src/avatar/Avatar.tsx, packages/core/CHANGELOG.md, packages/draggabletable/CHANGELOG.md, packages/fonts/CHANGELOG.md, packages/global/CHANGELOG.md, packages/icons/CHANGELOG.md, packages/notifications/CHANGELOG.md, packages/pagination/CHANGELOG.md, packages/popover/CHANGELOG.md, packages/sidebar/CHANGELOG.md, packages/table/CHANGELOG.md, packages/themes/CHANGELOG.md, packages/utils/CHANGELOG.md
* feat: add status for avatar [B1M2-3872]
* chore: small fix
Co-authored-by: Karl Kallavus <karl.kallavus@heathmont.net>
=> feat: add status for avatar [B1M2-3872] (#1390)

LICENSE, next-docs/components/Footer.tsx, next-docs/pages/index.tsx, packages/accordion/package.json, packages/assets/package.json, packages/calendar/package.json, packages/charts/package.json, packages/components/package.json, packages/core/package.json, packages/draggabletable/package.json, packages/fonts/package.json, packages/global/package.json, packages/icons/package.json, packages/notifications/package.json, packages/pagination/package.json, packages/popover/package.json, packages/sidebar/package.json, packages/table/package.json, packages/themes/package.json, packages/utils/package.json
=> feat: rename coingaming to yolo

next-docs/pages/components/radiobutton/radiobutton-api.tsx, packages/core/src/radioButton/RadioButtonInput.tsx
=> fix: add name prop to radioButton [B1M2-3880]

next-docs/pages/components/radiobutton/radiobutton.tsx, packages/core/src/radioButton/RadioButton.tsx, packages/core/src/radioButton/styles/RadioButtonHiddenInput.ts
=> fix: ts issue for radioButton [B1M2-3880]

package.json
=> test release

next-docs/styles/themes.css
=> fix(Betadda): fix betadda nextjs site theme switcher

next-docs/pages/components/chip.tsx, packages/components/src/chip/Chip.tsx
=> feat: extend Chip variants [B1M2-3932]

next-docs/pages/components/dialog/dialog.tsx, packages/components/src/dialog/Dialog.tsx, packages/components/src/dialog/private/layout.ts
=> feat: add new variant for dialog [B1M2-3870]

packages/themes/src/bombayClub/bombayClub.ts
=> fix: add smaller border radius to bombayclub theme [B1M2-3976]

packages/core/src/multiSelect/MultiSelect.tsx
=> fix: click outside closes MultiSelect

packages/components/src/chip/Chip.tsx
=> chore: render Chip as a button

packages/table/src/Table.tsx
=> feat(table.tsx): added useSortBy hook

packages/assets/.config/templates/svgr.template.icons.js, packages/icons/.config/templates/svgr.template.icons.js
Added all typed props to shouldForwardProps in icons -> assets, icons
It is ready to build after merge
=> B1 m2 4570 icon prop fix

.circleci/config.yml
=> ci: build next docs

packages/components/src/dialogContent/DialogContent.tsx
=> fix: remove Dialog internal padding

next-docs/pages/components/table/table.tsx, next-docs/public/examples/table/Sorting.tsx, packages/table/src/Table.tsx
=> fix(table.tsx): Fixed Table plugins order

next-docs/pages/components/popover.tsx, packages/popover/src/Popover.tsx, packages/popover/src/private/layout.ts
=> feat(popover.tsx): Added minWidth, maxWidth props to Popover

next-docs/public/examples/accordion/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/accordion/__tests__/index.test.tsx
=> fix: tests accordion

next-docs/public/examples/avatar/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/avatar/__tests__/index.test.tsx
=> feat: avatar tests

next-docs/pages/api/examples.ts
=> fix: check only Files not Directories for preview

packages/core/src/private/enums/Size.ts
=> feat: add sizes enum

packages/themes/src/livecasinoDark/livecasinoDark.ts, packages/themes/src/livecasinoLight/livecasinoLight.ts
=> fix: livecasino radius

next-docs/components/facing/News.tsx, next-docs/public/examples/datePicker/__tests__/__snapshots__/index.test.tsx.snap, packages/datepicker/src/DatePicker/private/day/Day.tsx
=> fix: update datepicker tests

next-docs/components/facing/News.tsx
=> feat: add 10 Guidelines to efficiently display data tables article link

next-docs/public/examples/datePicker/Calendar.tsx, next-docs/public/examples/datePicker/CalendarDisabledDay.tsx, next-docs/public/examples/datePicker/CalendarDisabledDays.tsx, next-docs/public/examples/datePicker/CalendarDisabledRange.tsx, next-docs/public/examples/datePicker/CalendarDisabledRange2.tsx, next-docs/public/examples/datePicker/DatePicker.tsx, next-docs/public/examples/datePicker/__tests__/__snapshots__/index.test.tsx.snap
=> fix: tests for datepicker

packages/accordion/src/private/layout.ts
=> feat: update Accordion with new tokens [B1M2-5072]

next-docs/components/Layout.tsx, next-docs/components/themes/BrandThemeSelector.tsx, next-docs/components/themes/DarkLightModeSwitch.tsx, next-docs/components/themes/DocsThemeProvider.tsx, next-docs/components/themes/RTLModeSwitch.tsx, next-docs/public/examples/datePicker/__tests__/__snapshots__/index.test.tsx.snap
=> Add rtl switch

next-docs/package.json, pnpm-lock.yaml
=> chore: upgrade next to v12.0.10

next-docs/public/examples/datePicker/Calendar.tsx, next-docs/public/examples/datePicker/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/datePicker/__tests__/index.test.tsx
=> fix: fix and update DP test with RTL

next-docs/jest.config.js, next-docs/public/examples/datePicker/__tests__/__snapshots__/index.test.tsx.snap
=> fix: jest timers: 'fake'

next-docs/public/examples/datePicker/Calendar.tsx, next-docs/public/examples/datePicker/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/datePicker/__tests__/index.test.tsx
=> fix: set Calendar date

next-docs/package.json, pnpm-lock.yaml
=> chore: add 'sharp' package for production Image Optimization for docs

packages/core/src/button/Button.tsx
=> fix(button): passing props

next-docs/pages/components/dialog/dialog.tsx, next-docs/public/examples/dialog/dialog/DialogHeader2.tsx, next-docs/public/examples/dialog/dialog/__tests__/__snapshots__/index.test.tsx.snap, packages/core/src/button/Button.tsx
=> Fix dialog new docs

next-docs/pages/components/select/multiSelect.tsx, next-docs/pages/components/select/singleSelect.tsx, next-docs/public/examples/select/multiReactSelect/Default.tsx, next-docs/public/examples/select/multiReactSelect/__tests__/index.test.tsx, next-docs/public/examples/select/singleReactSelect/Default.tsx, next-docs/public/examples/select/singleReactSelect/__tests__/index.test.tsx, packages/select/src/Select.tsx
=> feat: closeMenuOnSelect for MultiSelect [B1M2-5339]

next-docs/pages/components/datepickerRange.tsx, next-docs/public/examples/datePickerRange/Default.tsx, next-docs/public/examples/datePickerRange/__tests__/__snapshots__/index.test.tsx.snap, packages/datepicker/src/DateRangePicker/DateRangePicker.tsx, packages/datepicker/src/DateRangePicker/RangeCalendar.tsx, packages/datepicker/src/DateRangePicker/private/footer/Footer.tsx, packages/datepicker/src/DateRangePicker/private/hooks/useRangeCalendar.ts, packages/datepicker/src/DateRangePicker/private/picker/Picker.tsx, packages/datepicker/src/DateRangePicker/private/types/RangeConfig.ts, packages/datepicker/src/DateRangePicker/private/types/RangeTranslations.ts
=> fix(datepicker): typo

package.json, packages/core/package.json, packages/datepicker/package.json, packages/draggabletable/package.json, packages/popover/package.json, packages/table/package.json, packages/utils/package.json, pnpm-lock.yaml
=> chore: align polished version

next-docs/pages/colours.tsx
=> fix: color on color page

next-docs/pages/components/button.tsx, next-docs/pages/components/chip.tsx, next-docs/pages/components/loader.tsx
=> fix: add props table to button [MDS-29]

next-docs/public/examples/chip/__tests__/__snapshots__/index.test.tsx.snap, packages/core/src/chip/Chip.tsx
=> fix: set interactive chip border-radius [MDS-31]

packages/components/src/dialogContent/DialogContent.tsx
Arrows on badges carousel are hidden
=> fix: remove overflow:auto from DialogContent [CS-1303]

packages/components/src/withHorizontalScroll/withHorizontalScroll.ts
Subscribtion to observer cause an error on carousel unmount
=> fix: unobserve IntersectionObserver on unmount [CS-1304]

packages/assets/src/types/definitions/moon-themes.d.ts, packages/calendar/src/types/definitions/moon-themes.d.ts, packages/charts/src/types/definitions/moon-themes.d.ts, packages/core/src/private/enums/Size.ts, packages/draggabletable/src/types/definitions/moon-themes.d.ts, packages/icons/src/types/definitions/moon-themes.d.ts, packages/popover/src/types/definitions/moon-themes.d.ts, packages/table/src/types/definitions/moon-themes.d.ts, packages/themes/src/sharedTokens/sharedTokens.ts
=> fix: align size naming [MDS-62]

packages/components/src/dialog/private/toggle.ts, packages/components/src/private/icons/IconClose.tsx
=> Closing dialog fix

next-docs/pages/components/search.tsx, next-docs/public/examples/search/OmitResults.tsx, next-docs/public/examples/search/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/search/__tests__/index.test.tsx, packages/core/src/search/Search.tsx
=> MDS-21 add search without results popup

.circleci/config.yml, package.json
=> feat: add publish:workspaces

.circleci/config.yml, package.json
=> feat: add publish:workspaces (#1725)

pnpm-lock.yaml, workspaces/core/package.json, workspaces/core/src/button/private/buttonAnimations/AnimationContent.tsx, workspaces/core/src/checkbox/Checkbox.tsx, workspaces/core/src/private/icons/GenericCheckAlternative.tsx, workspaces/core/src/private/utils/inlineSvg/inlineSvg.ts, workspaces/core/src/private/utils/inlineSvg/mini-svg-data-uri.d.ts, workspaces/core/src/types/declarations/moon-icons.d.ts, workspaces/core/src/types/declarations/moon-utils.d.ts
=> fix: remove styled-component dependency

workspaces/core/src/checkbox/Checkbox.tsx, workspaces/core/src/chip/Chip.tsx
=> fix: small color fix for moon-tw

packages/themes/src/moneyballIoDark/moneyballIoDark.ts, packages/themes/src/moneyballIoLight/moneyballIoLight.ts, packages/themes/src/sharedTokens/sharedTokens.ts
Themes for moneyball.io were added
https://www.figma.com/file/pzk0Z3zJ9JlS5fRvNVRdH3/Web-app?node-id=17176%3A38243
=> feat: add moneyball.io themes [BASE1-2268]

next-docs/pages/core/checkbox.tsx, next-docs/styles/themes.css, workspaces/core/src/button/private/buttonSizes/buttonSizes.ts, workspaces/core/src/checkbox/Checkbox.tsx, workspaces/core/src/chip/Chip.tsx, workspaces/core/src/private/presets/ds-moon-preset.js
=> fix: add new border radius and fix checkbox

packages/themes/src/index.ts
Added missing export of theme to index.ts file
=> fix: add missing theme export to index file

next-docs/components/Layout.tsx, next-docs/components/ManifestLayout.tsx, next-docs/components/VisionLayout.tsx, next-docs/components/sidebar/ItemType.ts, next-docs/components/sidebar/Link.tsx, next-docs/components/sidebar/Logo.tsx, next-docs/components/sidebar/LogoLink.tsx, next-docs/components/sidebar/RecursiveNavItem.tsx, next-docs/components/sidebar/Sidebar.tsx, next-docs/components/sidebar/Version.tsx, next-docs/components/sidebar/recursiveIsCurrent.ts, next-docs/pages/core/accordion.tsx, next-docs/pages/core/button.tsx, next-docs/pages/core/checkbox.tsx, next-docs/pages/core/chip.tsx, next-docs/pages/core/loader.tsx, next-docs/pages/core/typography.tsx, next-docs/pages/index.tsx, next-docs/styles/themes.css, next-docs/tailwind.config.js, workspaces/core/src/accordion/Accordion.tsx, workspaces/core/src/chip/Chip.tsx, workspaces/core/src/chip/private/types/ChipProps.ts
=> fix: sidebar [MDS-104]

next-docs/pages/components/authCode.tsx, next-docs/public/examples/authCode/ErrorStateCentered.tsx, next-docs/public/examples/authCode/Stretch.tsx, packages/core/src/authCode/AuthCode.tsx, packages/core/src/authCode/styles/Container.tsx, packages/core/src/authCode/styles/MessageWrapper.tsx
=> Fix and improve auth code

next-docs/components/CodeSnippet.tsx, next-docs/pages/components/accordion.tsx, next-docs/pages/components/listItem.tsx, next-docs/public/examples/accordionNew/Sizes.tsx, next-docs/public/examples/listItem/SingleLineItemSize.tsx, next-docs/public/examples/listItem/TwoLineItemsSize.tsx, packages/core/src/accordion/Accordion.tsx, packages/core/src/listItem/ListItem.tsx
=> MDS-70 make medium default size everywhere

next-docs/pages/components/textInputGroup.tsx, next-docs/public/examples/textInputGroup/Combined.tsx, next-docs/public/examples/textInputGroup/CombinedVertical.tsx, next-docs/public/examples/textInputGroup/EventListenerSelect.tsx, next-docs/public/examples/textInputGroup/MultiSelect.tsx, next-docs/public/examples/textInputGroup/SingleSelect.tsx, next-docs/public/examples/textInputGroup/SingleSelectRtl.tsx, next-docs/public/examples/textInputGroup/SingleSelectVertical.tsx, next-docs/public/examples/textInputGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/select/src/TextInputGroup.tsx, packages/select/src/private/SelectGroupEnd.tsx, packages/select/src/private/SelectGroupStart.tsx, packages/select/src/private/types/CombinedGroupProps.ts, packages/select/src/private/types/CombinedInputProps.ts, packages/select/src/private/types/CombinedInputSize.ts, packages/select/src/private/types/OrientationType.tsx, packages/select/src/styles/Container.tsx
=> Refactor TextInputGroup component to support combined inputs

packages/select/package.json, packages/select/src/private/ClearIndicator.tsx, packages/select/src/private/DropdownIndicator.tsx, packages/select/src/private/MultiValueRemove.tsx, packages/select/src/private/icons/ControlsChevronDown.tsx, packages/select/src/private/icons/ControlsChevronUp.tsx, packages/select/src/private/icons/ControlsClose.tsx, pnpm-lock.yaml
=> fix: select icons

next-docs/components/sidebar/navigation.ts, next-docs/pages/core/pagination.tsx, next-docs/public/examples/paginationTW/Default.tsx, next-docs/tailwind.config.js, workspaces/core/src/index.ts, workspaces/core/src/pagination/Pagination.tsx, workspaces/core/src/pagination/private/icons/ChevronLeft.tsx, workspaces/core/src/pagination/private/icons/ChevronRight.tsx, workspaces/core/src/pagination/private/types/PaginationTypes.ts
=> MDS-97 Pagination component

next-docs/public/examples/authCode/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/textInput/date/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/textInput/datetime/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/textInput/email/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/textInput/number/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/textInput/password/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/textInput/search/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/textInput/telephone/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/textInput/text/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/textInput/time/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/textInput/url/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/textInputGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/core/src/textInput/private/TextInputBasic.tsx, packages/core/src/textInput/private/TextInputInnerLabel.tsx, packages/core/src/textInput/private/TextInputPasswort.tsx
=> fix: textInput correct props for container

packages/core/src/authCode/AuthCode.tsx, packages/core/src/authCode/private/useDebounce.tsx
=> Fix auth code fast typing

next-docs/public/examples/authCode/__tests__/__snapshots__/index.test.tsx.snap, packages/core/src/authCode/AuthCode.tsx
=> feat: add data-testid to AuthCode

.npmrc, next-docs/public/examples/carousel/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/search/__tests__/__snapshots__/index.test.tsx.snap, pnpm-lock.yaml
=> fix: peer deps

next-docs/pages/components/textInputGroup.tsx, next-docs/public/templates/styles/bc-template.css, next-docs/styles/bc-template-input.css
=> feat: add css for bc template

workspaces/templates/README.mdx, workspaces/templates/package.json, workspaces/templates/src/bc-template.css, workspaces/templates/src/bc-template.min.css, workspaces/templates/src/sb-template.css, workspaces/templates/src/sb-template.min.css, workspaces/templates/tsconfig.cjs.json, workspaces/templates/tsconfig.esm.json
=> feat: add moon-templates package

packages/components/src/tabLink/TabLink.tsx
=> fix: revert back link states styling

.gitignore, next-docs/tailwind.config.js, workspaces/templates/src/bc-template.css, workspaces/templates/src/bc-template.min.css, workspaces/templates/src/sb-template.css, workspaces/templates/src/sb-template.min.css
=> fix: add new css template with all classes

packages/components/src/carousel/Carousel.tsx, packages/components/src/carousel/control.tsx
=> fix: fix carousel contol arrows showing

next-docs/pages/core/accordion.tsx, next-docs/public/examples/accordionTW/Background.tsx, next-docs/public/examples/accordionTW/WithoutButton.tsx, next-docs/public/examples/accordionTW/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/accordionTW/__tests__/index.test.tsx, workspaces/core/src/accordion/Accordion.tsx, workspaces/core/src/accordion/private/types/AccordionProps.ts
=> fix: Accordion tw title prop and bgColor [MDS-179]

next-docs/pages/templates/sportsbet/vip.tsx
=> fix: changed bg color for accordion

next-docs/components/facing/PageTitle.tsx
=> fix: add link to Elixir [MDS-180]

packages/themes/src/empireDark/empireDark.ts, packages/themes/src/empireLight/empireLight.ts
New design of Empire.io site requires new colors
=> feat: change colors of empire theme [CS-1848]

packages/themes/src/empireDark/empireDark.ts, packages/themes/src/empireLight/empireLight.ts
Changed secondary color according to design changes
=> fix: change color hit in empire theme [CS-1848]

next-docs/components/search/RenderResults.tsx, next-docs/components/search/SearchButton.tsx
=> fix: remove classes for dark theme

next-docs/components/templates/cta.tsx, next-docs/components/templates/explore-carousel-item.tsx, next-docs/components/templates/hero.tsx, next-docs/pages/templates/bitcasino/vip.tsx
=> fix: Fixed light theme for bitcasino

next-docs/components/ComponentPageDescription.tsx, next-docs/components/PageSection.tsx, next-docs/components/facing/ForDesigners.tsx, next-docs/components/facing/ForDevelopers.tsx, next-docs/components/facing/Updates.tsx, next-docs/components/gettingStarted/DesDevSwitch.tsx, next-docs/components/gettingStarted/DesGettingStarted.tsx, next-docs/components/gettingStarted/DevGettingStarted.tsx, next-docs/components/sidebar/RecursiveNavItem.tsx, next-docs/pages/gettingStarted.tsx, next-docs/pages/gettingStartedDevs.tsx
=> feat: add for designers page [MDS-196]

pnpm-lock.yaml, workspaces/themes/src/treadart.css
=> feat: add TreadArt theme [MDS-198]

next-docs/components/settings/elixir/ElixirSettings.tsx, next-docs/components/settings/react/ReactSettings.tsx
=> feat: remove internal brands [MDS-200]

next-docs/components/Header.tsx, next-docs/components/facing/ForDesigners.tsx, next-docs/components/facing/ForDevelopers.tsx
=> fix: mobile logo link and main page links [MDS-210]

workspaces/tables/src/func/Table.tsx, workspaces/tables/src/styled/StyledTable.ts, workspaces/themes/next/tradeart.css, workspaces/themes/src/tradeart.css
=> fix: table component [MDS-47]

next-docs/public/examples/tableTW/Default.tsx, next-docs/tailwind.config.js, workspaces/core/src/select/Select.tsx, workspaces/tables/src/func/Table.tsx, workspaces/tables/src/index.ts, workspaces/tables/src/styled/StyledTable.ts, workspaces/tables/src/utils/classnames.ts
=> fix: fixes for table and select tw

next-docs/public/examples/selectTw/single/__tests__/__snapshots__/index.test.tsx.snap, pnpm-lock.yaml, workspaces/core/package.json, workspaces/core/src/select/Select.tsx, workspaces/core/src/select/private/Options.tsx
=> feat: add positioning for options

next-docs/pages/core/switch.tsx, next-docs/public/examples/switchTW/codeExamples/Sizes.tsx, next-docs/public/examples/switchTW/codeExamples/SizesWithIcons.tsx
=> feat: add code examples for switch TW

workspaces/core/src/checkbox/Checkbox.tsx, workspaces/core/src/checkbox/private/types/CheckboxProps.ts
=> fix: id as optional props for tw checkbox

next-docs/components/facing/DeprecationWarning.tsx, next-docs/pages/components/accordion.tsx, next-docs/pages/components/avatar.tsx, next-docs/pages/components/button.tsx, next-docs/pages/components/checkbox.tsx, next-docs/pages/components/chip.tsx, next-docs/pages/components/icons.tsx, next-docs/pages/components/label.tsx, next-docs/pages/components/loader.tsx, next-docs/pages/components/radiobutton.tsx, next-docs/pages/components/select/singleSelect.tsx, next-docs/pages/components/switch.tsx, next-docs/pages/components/table.tsx, next-docs/pages/components/textInput/date.tsx, next-docs/pages/components/textInput/dateTime.tsx, next-docs/pages/components/textInput/email.tsx, next-docs/pages/components/textInput/number.tsx, next-docs/pages/components/textInput/password.tsx, next-docs/pages/components/textInput/search.tsx, next-docs/pages/components/textInput/telephone.tsx, next-docs/pages/components/textInput/text.tsx, next-docs/pages/components/textInput/time.tsx, next-docs/pages/components/textInput/url.tsx, next-docs/pages/components/textInputGroup.tsx, next-docs/pages/components/typography/caption.tsx, next-docs/pages/components/typography/heading.tsx, next-docs/pages/components/typography/text.tsx
=> fix: add DeprecationWarning as a component

next-docs/pages/core/chip.tsx, next-docs/public/examples/chipTW/AsLink.tsx, next-docs/public/examples/chipTW/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/chipTW/__tests__/index.test.tsx, workspaces/core/src/chip/Chip.tsx, workspaces/core/src/chip/private/types/ChipProps.ts
=> feat: add polymorphic Chip [MDS-235]

next-docs/public/examples/dialog/dialog/DialogHeader2.tsx, next-docs/public/examples/popover/Default.tsx, next-docs/public/examples/popover/__tests__/__snapshots__/index.test.tsx.snap
=> chore: add examples for Popover and Dialog for closing on inner button

next-docs/components/gettingStarted/DevGettingStarted.tsx, workspaces/core/src/button/Button.tsx, workspaces/core/src/button/private/types/ButtonProps.ts, workspaces/core/src/button/styles/ButtonComponent.tsx
=> fix: add classname support to Button [MDS-263]

workspaces/themes/src/lab.css, workspaces/themes/src/partners.css
=> feat: add lab and partners themes [MDS-265]

workspaces/core/src/switch/Switch.tsx
=> fix: add useEffect for Switch external state

next-docs/next.config.js, next-docs/package.json, package.json, pnpm-lock.yaml, workspaces/core/package.json, workspaces/tables/package.json
=> fix: add analyzer and fix modules

next-docs/CHANGELOG.md, next-docs/package.json, pnpm-lock.yaml, workspaces/core/CHANGELOG.md, workspaces/core/package.json, workspaces/tables/CHANGELOG.md, workspaces/tables/package.json, workspaces/templates/CHANGELOG.md, workspaces/templates/package.json
=> chore: bump moon version to 9.12.0

next-docs/public/examples/popover/__tests__/index.test.tsx
=> fix: PopoverPortal type

next-docs/public/examples/popover/__tests__/index.test.tsx, next-docs/public/examples/tableTW/__tests__/__snapshots__/index.test.tsx.snap, workspaces/tables/src/components/TD.tsx
=> Fix table cell width

next-docs/CHANGELOG.md, next-docs/package.json, pnpm-lock.yaml, workspaces/core/CHANGELOG.md, workspaces/core/package.json, workspaces/tables/CHANGELOG.md, workspaces/tables/package.json
=> chore: bump moon version to 9.12.1

workspaces/themes/src/sportsbet.css
=> fix: set correct beerus color for theme-sb-light

next-docs/public/examples/tableTW/__tests__/__snapshots__/index.test.tsx.snap, workspaces/tables/src/components/TH.tsx
=> Fix th width

workspaces/themes/package.json, workspaces/themes/src/index.ts
=> fix: trigger release

workspaces/themes/CHANGELOG.md, workspaces/themes/package.json
=> chore: bump moon version to 9.12.4

next-docs/public/examples/breadcrumbsTW/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/buttonTW/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/dropdownTW/Select.tsx, next-docs/public/examples/dropdownTW/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/labelTW/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/textInputGroupTW/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/button/private/buttonSizes/buttonSizes.ts, workspaces/core/src/label/styles/LabelContainer.tsx, workspaces/core/src/textInputGroup/styles/Container.tsx
=> fix: broken components [MDS-280]

next-docs/public/examples/modalTW/__tests__/__snapshots__/index.test.tsx.snap
=> chore: bump snapshots

packages/themes/src/sportsbetDark/sportsbetDark.ts, packages/themes/src/sportsbetLight/sportsbetLight.ts
Updated the colors for Sportsbet Dark and Light themes
=> feat: news colors for SB themes [BASE1-3319]

next-docs/public/examples/dropdownTW/Default.tsx, next-docs/public/examples/dropdownTW/OptionsVariants.tsx, next-docs/public/examples/dropdownTW/Select.tsx, next-docs/public/examples/dropdownTW/SelectStates.tsx, next-docs/public/examples/dropdownTW/TriggerElements.tsx, workspaces/core/src/dropdown/Dropdown.tsx, workspaces/core/src/modal/Modal.tsx
=> fix: ts issue for Dropdown and Modal

next-docs/components/sidebar/navigation.ts, next-docs/pages/core/authcode.tsx, next-docs/public/examples/authCodeTW/Default.tsx, next-docs/public/examples/authCodeTW/ErrorState.tsx, next-docs/public/examples/authCodeTW/FourChars.tsx, next-docs/public/examples/authCodeTW/OnlyDigits.tsx, next-docs/public/examples/authCodeTW/Stretch.tsx, next-docs/public/examples/authCodeTW/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/authCodeTW/__tests__/index.test.tsx, workspaces/core/src/authCode/AuthCode.tsx, workspaces/core/src/authCode/private/useDebounce.tsx, workspaces/core/src/index.ts
It should provide the same functionality as styled AuthCode component. the logic is same, just used tailwind classes to re-style the component
=> feat: authCode for tailwind [NC-212]

workspaces/core/src/select/private/Options.tsx, workspaces/core/src/textInput/private/Input.tsx
=> fix: Select and TextInput

packages/themes/src/bombayClub/bombayClub.ts
=> fix: update bombay theme

workspaces/themes/src/sportsbet.css
https://www.figma.com/file/nqyuJ9qa3xNSIel6uhOqhT/Sportsbet-Web?node-id=18411%3A208611&t=0c3XRH6M6ofEYFUw-0
=> Fix: update sb dark colors due to new palette

workspaces/core/src/popover/Popover.tsx
=> fix: popover correct width

next-docs/components/templates/cta.tsx, next-docs/components/templates/header.tsx, next-docs/components/templates/hero.tsx, next-docs/components/templates/social.tsx, next-docs/pages/templates/bitcasino/vip.tsx
=> fix: buttons on bitcasino vip template [MDS-313]

next-docs/components/sidebar/RecursiveNavItem.tsx, next-docs/components/sidebar/navigation.ts, next-docs/pages/components/tooltip.tsx, next-docs/pages/core/tooltip.tsx, next-docs/public/examples/tooltipTW/ArrowPositions.tsx, next-docs/public/examples/tooltipTW/Customization.tsx, next-docs/public/examples/tooltipTW/Default.tsx, next-docs/public/examples/tooltipTW/WithoutArrow.tsx, next-docs/public/examples/tooltipTW/WithoutShadow.tsx, next-docs/public/examples/tooltipTW/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/tooltipTW/__tests__/index.test.tsx, pnpm-lock.yaml, workspaces/core/package.json, workspaces/core/src/index.ts, workspaces/core/src/tooltip/Tooltip.tsx, workspaces/core/src/utils/mergeClassnames.ts
=> feat: add tooltip component [MDS-314]

next-docs/pages/core/accordion.tsx, next-docs/public/examples/accordionTW/Background.tsx, next-docs/public/examples/accordionTW/ContentHeader.tsx, next-docs/public/examples/accordionTW/ContentOutside.tsx, next-docs/public/examples/accordionTW/ContentOutsideSizes.tsx, next-docs/public/examples/accordionTW/Default.tsx, next-docs/public/examples/accordionTW/Disabled.tsx, next-docs/public/examples/accordionTW/Divider.tsx, next-docs/public/examples/accordionTW/OpenDefault.tsx, next-docs/public/examples/accordionTW/Single.tsx, next-docs/public/examples/accordionTW/Sizes.tsx, next-docs/public/examples/accordionTW/__tests__/__snapshots__/index.test.tsx.snap
**Accordion**
* changed _ControlsChevronRight_ to _ControlsChevronDown_ in examples
* added _ComponentAnatomy_
* changed _transition-200_ classname to _duration-200_
* use examples.Single for _Single_ example
=> fix: accordion arrows and Single examle

next-docs/pages/core/dropdown.tsx, next-docs/public/examples/dropdown/Select.tsx, workspaces/core/src/dropdown/Dropdown.tsx, workspaces/core/src/selectButton/SelectButton.tsx
=> fix: add classNames for Dropdown

next-docs/components/ComponentPageDescription.tsx, next-docs/components/codePreview/Preview.tsx, next-docs/pages/core/tabs.tsx, next-docs/public/examples/tabs/Segment.tsx, next-docs/public/examples/tabs/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/tabs/__tests__/index.test.tsx, workspaces/core/src/tabs/Tabs.tsx, workspaces/core/src/tabs/private/types/ListProps.ts, workspaces/core/src/tabs/private/types/PanelProps.ts, workspaces/core/src/tabs/private/types/Size.ts, workspaces/core/src/tabs/private/types/TabProps.ts, workspaces/core/src/tabs/private/types/TabsProps.ts, workspaces/core/src/tabs/private/types/TabsState.ts, workspaces/core/src/tabs/private/utils/TabsContext.ts, workspaces/core/src/tabs/private/utils/getTabSize.ts, workspaces/core/src/tabs/private/utils/useTabsContext.ts
=> feat: add segment to Tabs [MDS-335]

workspaces/core/src/menuItem/MenuItem.tsx
=> fix: add ts for MenuItem.Title

next-docs/pages/components/carousel.tsx, next-docs/pages/core/carousel.tsx
=> fix: add deprecation warning [MDS-347]

next-docs/components/breadcrumbs/Breadcrumbs.tsx, next-docs/pages/core/tabs.tsx, next-docs/pages/core/tooltip.tsx, next-docs/pages/templates/bitcasino/vip.tsx, next-docs/pages/templates/sportsbet/vip.tsx, next-docs/types/definition/core.d.ts, workspaces/core/src/tabs/private/types/TabsProps.ts
=> fix: add typed index to onChange [MDS-355]

next-docs/components/gettingStarted/DesGettingStarted.tsx, next-docs/components/gettingStarted/DevGettingStarted.tsx, next-docs/components/gettingStarted/DuoThemeExample.tsx, next-docs/components/gettingStarted/SingleThemeExample.tsx, next-docs/components/gettingStarted/TailwindGettingStarted.tsx, next-docs/components/search/SearchProvider.tsx, next-docs/components/templates/headline.tsx, next-docs/components/templates/social.tsx, next-docs/components/templates/title.tsx, next-docs/pages/colours.tsx, next-docs/pages/gettingStarted.tsx, next-docs/pages/howToContribute.tsx, next-docs/pages/manifest.tsx, next-docs/pages/templates/bitcasino/vip.tsx, next-docs/pages/templates/sportsbet/vip.tsx, next-docs/pages/tokens.tsx, next-docs/pages/vision.tsx, next-docs/public/examples/menuItem/MultiTitle.tsx, next-docs/public/examples/menuItem/WithIcon.tsx, next-docs/public/examples/menuItem/WithMeta.tsx, next-docs/public/examples/menuItem/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/modal/StyledContent.tsx, next-docs/public/examples/modal/WithSelect.tsx, next-docs/public/examples/popover/Default.tsx, next-docs/public/examples/popover/WithClose.tsx
=> fix: update docs [MDS-356]

workspaces/themes/src/sportsbet.css
Update Sportsbet theme settings for border radius values.
=> feat: Update sportsbet border radiuses

next-docs/pages/core/button.tsx, next-docs/public/transformIcon/IconPreview.tsx, workspaces/core/src/button/private/types/ButtonAnimations.ts
=> fix: add boolean to animation props [MDS-366]

next-docs/pages/core/carousel.tsx, next-docs/public/examples/carousel/SelectIndex.tsx, next-docs/public/examples/carousel/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/carousel/__tests__/index.test.tsx, workspaces/core/src/carousel/Carousel.tsx
=> feat: scroll carousel on selectedIndex change

next-docs/pages/core/dropdown.tsx, next-docs/public/examples/dropdown/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/form/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/popover/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/dropdown/Dropdown.tsx
=> fix: use popper in a proper way in  Dropdown

next-docs/components/Settings.tsx, next-docs/components/brandSwitcher/BrandSwitcher.tsx, next-docs/components/themes/useThemes.tsx, next-docs/components/themes/useThemesTW.tsx, next-docs/public/examples/popover/__tests__/__snapshots__/index.test.tsx.snap, next-docs/styles/themes.css, next-docs/utils/useSettings.ts, workspaces/core/src/popover/Popover.tsx, workspaces/core/src/popover/private/types/PopoverRootProps.ts, workspaces/themes/src/bombayClub.css, workspaces/themes/src/index.ts
=> feat: add brands switching fix and use Popover [MDS-371]

next-docs/pages/core/modal.tsx, next-docs/pages/core/switch.tsx
=> fix: typos

next-docs/public/examples/search/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/search/private/components/Input.tsx, workspaces/core/src/search/private/components/Search.tsx, workspaces/core/src/search/private/components/SearchModal.tsx
=> fix: Search component

next-docs/pages/core/search.tsx, next-docs/public/examples/search/Default.tsx, workspaces/core/src/search/private/components/Input.tsx, workspaces/core/src/search/private/components/Search.tsx
=> fix: set autoFocus as props for search

next-docs/public/examples/popover/WithClose.tsx
=> fix: trigger PR

workspaces/core/src/private/presets/ds-moon-preset.js
Added lost comma in font family
=> fix: averta font

next-docs/styles/themes.css, packages/themes/src/newBitcasinoDark/newBitcasinoDark.ts, packages/themes/src/newBitcasinoLight/newBitcasinoLight.ts, workspaces/themes/src/bitcasinoNew.css, workspaces/themes/src/index.ts
Theme for the new design https://www.figma.com/file/VvtFa57PsrjF7BaMJ61X29/Bitcasino-New---Theme?node-id=1016%3A324&t=UALKtC60tPzOW2K7-0
=> feat: add new Bitcasino theme

workspaces/core/src/drawer/private/types/DrawerRootProps.ts, workspaces/core/src/drawer/private/types/PanelProps.ts, workspaces/core/src/drawer/private/utils/getPositionStyles.ts
=> fix: Drawer width [MDS-426]

next-docs/public/examples/accordion/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/popover/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/accordion/Accordion.tsx, workspaces/core/src/accordion/private/types/ButtonProps.ts, workspaces/core/src/accordion/private/types/ContentProps.ts, workspaces/core/src/accordion/private/types/HeaderProps.ts, workspaces/core/src/accordion/private/utils/AccordionContext.ts, workspaces/core/src/accordion/private/utils/AccordionItemContext.ts, workspaces/core/src/accordion/private/utils/useAccordionContext.ts, workspaces/core/src/accordion/private/utils/useAccordionItemContext.ts, workspaces/core/src/popover/Popover.tsx
=> fix: Accordion overlay content [MDS-352]

pnpm-lock.yaml, workspaces/core/package.json, workspaces/core/src/alert/Alert.tsx, workspaces/core/src/avatar/Avatar.tsx, workspaces/core/src/breadcrumb/private/Collapsed.tsx, workspaces/core/src/breadcrumb/private/Extended.tsx, workspaces/core/src/button/private/utils/buttonAnimations/AnimationContent.tsx, workspaces/core/src/checkbox/Checkbox.tsx, workspaces/core/src/combobox/Combobox.tsx, workspaces/core/src/group/private/InsetSelect.tsx, workspaces/core/src/group/private/Select.tsx, workspaces/core/src/iconButton/private/utils/buttonAnimations/AnimationContent.tsx, workspaces/core/src/menuItem/MenuItem.tsx, workspaces/core/src/private/icons/ArrowsRight.tsx, workspaces/core/src/private/icons/ControlsChevronDownSmall.tsx, workspaces/core/src/private/icons/ControlsClose.tsx, workspaces/core/src/private/icons/ControlsCloseSmall.tsx, workspaces/core/src/private/icons/GenericCheckAlternative.tsx, workspaces/core/src/private/icons/GenericSearch.tsx, workspaces/core/src/private/icons/GenericUser.tsx, workspaces/core/src/private/icons/Other3DotsHorizontal.tsx, workspaces/core/src/search/private/components/Input.tsx, workspaces/core/src/search/private/components/Trigger.tsx, workspaces/core/src/select/private/InputBtn.tsx, workspaces/core/src/selectButton/SelectButton.tsx, workspaces/core/src/snackbar/Snackbar.tsx
=> feat: MDS-438 use inline svg icons for workspases/core

next-docs/__mocks__/ResizeObserver.js, next-docs/package.json, next-docs/public/examples/modal/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/modal/__tests__/index.test.tsx, pnpm-lock.yaml
=> fix: rewrite Modal tests [MDS-454]

next-docs/components/sidebar/navigation.ts, next-docs/pages/core/select.tsx
=> fix: deprecate Select components [MDS-469]

next-docs/public/examples/tooltip/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/tooltip/__tests__/index.test.tsx
=> fix: Tooltip unit test [MDS-464]

.config/docker/docs/Dockerfile, README.md, next-docs/pages/howToContribute.tsx
=> fix(ci): pnpm version

workspaces/core/src/radio/private/types/RadioProps.ts
=> fix: RadioProps onChange type

next-docs/components/Footer.tsx, next-docs/components/Settings.tsx, next-docs/components/sidebar/LogoLink.tsx, next-docs/components/sidebar/Sidebar.tsx, next-docs/components/sidebar/Version.tsx
=> fix: update footer

packages/themes/src/newBitcasinoDark/newBitcasinoDark.ts, packages/themes/src/newBitcasinoLight/newBitcasinoLight.ts, workspaces/themes/src/bitcasinoNew.css
Changed piccolo colour for dark and light Bitcasino themes
=> feat: new piccolo colour for Bitcasino

.config/docker/docs/Dockerfile
=> fix(ci): node version for docker

next-docs/public/examples/search/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/search/private/components/Search.tsx
=> fix(search): top position css

next-docs/pages/components/accordion.tsx, next-docs/public/examples/accordion/ControlOutside.tsx, next-docs/public/examples/accordion/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/accordion/__tests__/index.test.tsx, workspaces/core/src/accordion/Accordion.tsx, workspaces/core/src/accordion/private/types/AccordionProps.ts, workspaces/core/src/accordion/private/types/AccordionRootProps.ts, workspaces/core/src/accordion/private/types/ItemProps.ts
=> feat: MDS-445 accordion control outside

packages/themes/src/newBitcasinoDark/newBitcasinoDark.ts, packages/themes/src/newBitcasinoLight/newBitcasinoLight.ts, workspaces/themes/src/bitcasinoNew.css
=> feat: change beerus colour for bitcasino [CS-4180]

next-docs/components/search/RenderResults.tsx, next-docs/components/search/SearchButton.tsx, next-docs/components/search/SearchProvider.tsx, next-docs/components/search/hooks/useSearch.tsx, next-docs/components/search/utils/getActions.ts, next-docs/package.json, next-docs/pages/components/searchCmdk.tsx, pnpm-lock.yaml, workspaces/core/src/searchCmdk/SearchCmdk.tsx
=> MDS-522 replace search in moon

next-docs/pages/components/menuItem.tsx, next-docs/public/examples/menuItem/MultiTitle.tsx, next-docs/public/examples/menuItem/__tests__/__snapshots__/index.test.tsx.snap
=> fix: MDS-292 MenuItem

next-docs/public/transformIcon/.config/svgr.config.dimensions.js, next-docs/public/transformIcon/.config/svgr.config.js, next-docs/public/transformIcon/.config/templates/template_tw.svgrrc.js
=> feat: MDS-523 Replace transform Svg page for TW

next-docs/public/examples/combobox/Default.tsx
=> chore: add nullable to Default combobox

next-docs/public/examples/combobox/Default.tsx
=> fix: return nullable prop to the second example at the Default section

next-docs/pages/components/dropdown.tsx, next-docs/public/examples/dropdown/HiddenInput.tsx, next-docs/public/examples/dropdown/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/dropdown/__tests__/index.test.tsx, workspaces/core/src/dropdown/Dropdown.tsx
=> chore: MDS-540 add hidden input

next-docs/components/GoogleAnalytics.tsx, next-docs/pages/_app.tsx
=> feat: add Google Analytics [MDS-542]

next-docs/pages/components/button.tsx, next-docs/pages/components/iconButton.tsx, workspaces/core/src/button/Button.tsx, workspaces/core/src/button/private/types/ButtonSettingsProps.ts, workspaces/core/src/button/styles/ButtonComponent.tsx
=> fix: update Button [MDS-546]

next-docs/pages/components/switch.tsx, next-docs/public/examples/switch/CustomBg.tsx, next-docs/public/examples/switch/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/switch/Switch.tsx, workspaces/core/src/switch/private/types/Props.ts
=> fix: update Switch [MDS-547]

next-docs/components/Header.tsx, next-docs/components/facing/CardArticle.tsx, next-docs/components/facing/CardContibutor.tsx, next-docs/components/facing/ForDesigners.tsx, next-docs/components/facing/ForDevelopers.tsx, next-docs/components/sidebar/LogoLink.tsx, next-docs/public/examples/popover/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/popover/__tests__/index.test.tsx, workspaces/core/src/popover/Popover.tsx
=> fix: improve accessibility on the main page [MDS-548]

next-docs/public/examples/pagination/WithButtons.tsx, next-docs/public/examples/pagination/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/pagination/Pagination.tsx, workspaces/core/src/pagination/private/hooks/usePagination.ts, workspaces/core/src/pagination/private/hooks/usePaginationContext.ts, workspaces/core/src/pagination/private/types/ChildrenFunc.ts, workspaces/core/src/pagination/private/types/NextPrevButtonProps.ts, workspaces/core/src/pagination/private/types/PagesProps.ts, workspaces/core/src/pagination/private/types/PaginationContext.ts, workspaces/core/src/pagination/private/types/PaginationProps.ts, workspaces/core/src/pagination/private/types/PolymorphicNextPrevButtonProps.ts, workspaces/core/src/pagination/private/types/PolymorphicPagesProps.ts, workspaces/core/src/pagination/private/types/PropsWithChildrenFunc.ts, workspaces/core/src/pagination/private/types/TruncableElementProps.ts, workspaces/core/src/pagination/private/types/UsePagination.ts, workspaces/core/src/pagination/private/types/WithChildren.ts
=> fix: Pagination styles [MDS-549]

next-docs/public/examples/authCode/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/authCode/AuthCode.tsx
=> fix: authCode dark theme

package.json, pnpm-lock.yaml
=> feat: update typescript

next-docs/public/examples/authCode/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/authCode/AuthCode.tsx
=> fix: authcode padding

next-docs/pages/components/textarea.tsx, next-docs/public/examples/form/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/textarea/WithBtn.tsx, next-docs/public/examples/textarea/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/textarea/__tests__/index.test.tsx, workspaces/core/src/private/presets/ds-moon-preset.js, workspaces/core/src/textarea/Textarea.tsx
=> feat: MDS-556 add textArea with btn exmpl

next-docs/pages/components/switch.tsx, next-docs/pages/components/tooltip.tsx, next-docs/public/examples/switch/WithTooltip.tsx, next-docs/public/examples/switch/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/switch/__tests__/index.test.tsx, next-docs/public/examples/tooltip/NotPortal.tsx, next-docs/public/examples/tooltip/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/tooltip/__tests__/index.test.tsx, workspaces/core/src/switch/Switch.tsx, workspaces/core/src/tooltip/Tooltip.tsx, workspaces/core/src/tooltip/private/types/ContentProps.ts
=> fix: MDS-559 align switch and tooltip 

next-docs/public/examples/combobox/Default.tsx, next-docs/public/examples/combobox/InsetMultiSelect.tsx, next-docs/public/examples/combobox/InsetSelect.tsx, next-docs/public/examples/combobox/InsetSelectStates.tsx, next-docs/public/examples/combobox/MultiSelect.tsx, next-docs/public/examples/combobox/Select.tsx, next-docs/public/examples/combobox/SelectStates.tsx, next-docs/public/examples/combobox/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/combobox/Combobox.tsx, workspaces/core/src/combobox/private/types/ComboboxState.ts, workspaces/core/src/combobox/private/types/InputProps.ts
=> fix: combobox

next-docs/pages/components/pagination.tsx, next-docs/public/examples/pagination/WithHref.tsx, next-docs/public/examples/pagination/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/pagination/__tests__/index.test.tsx, workspaces/core/src/pagination/Pagination.tsx, workspaces/core/src/pagination/private/hooks/usePagination.ts, workspaces/core/src/pagination/private/types/PaginationContext.ts, workspaces/core/src/pagination/private/types/PaginationProps.ts, workspaces/core/src/pagination/private/types/UsePagination.ts
=> feat: add href to Pagination [MDS-570]

next-docs/public/examples/carousel/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/carousel/Carousel.tsx, workspaces/core/src/popover/Popover.tsx
=> fix: MDS-582 added rest props for carousel and popover

workspaces/core/src/carousel/Carousel.tsx
=> feat: MDS-586 Carousel fix useInterval

workspaces/base/src/accordion/Accordion.tsx
=> fix accordion base

next-docs/pages/components/progress.tsx, next-docs/public/examples/alert/Customization.tsx, next-docs/public/examples/alert/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/progress/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/radio/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/alert/Alert.tsx, workspaces/core/src/progress/Progress.tsx, workspaces/core/src/radio/Radio.tsx
=> fix: Alert, Progress and Radio accessibility [MDS-599]

next-docs/pages/components/breadcrumb.tsx, next-docs/pages/components/iconButton.tsx, next-docs/public/examples/breadcrumbs/CustomDivider.tsx, next-docs/public/examples/breadcrumbs/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/button/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/drawer/Close.tsx, next-docs/public/examples/drawer/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/iconButton/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/loader/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/breadcrumb/Breadcrumb.tsx, workspaces/core/src/breadcrumb/private/Collapsed.tsx, workspaces/core/src/breadcrumb/private/Extended.tsx, workspaces/core/src/breadcrumb/private/types/Props.ts, workspaces/core/src/iconButton/IconButton.tsx, workspaces/core/src/iconButton/private/utils/AnimationContent.tsx, workspaces/core/src/iconButton/private/utils/getAriaLabel.ts, workspaces/core/src/iconButton/private/utils/getButtonSize.ts, workspaces/core/src/iconButton/styles/IconButtonComponent.tsx, workspaces/core/src/loader/Loader.tsx
=> fix: Breadcrumb and IconButton accessibility [MDS-603]

next-docs/public/examples/dropdown/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/menuItem/AsLink.tsx, next-docs/public/examples/menuItem/Checkbox.tsx, next-docs/public/examples/menuItem/ExpandCollapse.tsx, next-docs/public/examples/menuItem/MultiTitle.tsx, next-docs/public/examples/menuItem/Radio.tsx, next-docs/public/examples/menuItem/WithIcon.tsx, next-docs/public/examples/menuItem/WithMeta.tsx, next-docs/public/examples/menuItem/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/popover/TriggerElements.tsx, next-docs/public/examples/popover/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/menuItem/MenuItem.tsx, workspaces/core/src/menuItem/private/types/CheckboxRadioProps.ts, workspaces/core/src/menuItem/private/types/MenuItemComponentProps.ts, workspaces/core/src/menuItem/private/types/MenuItemPolymorphicProps.ts, workspaces/core/src/menuItem/private/types/MenuItemProps.ts, workspaces/core/src/menuItem/private/types/MenuItemState.ts, workspaces/core/src/menuItem/private/types/MultiTitleProps.ts, workspaces/core/src/menuItem/private/utils/MenuItemContext.ts, workspaces/core/src/menuItem/private/utils/useMenuItemContext.ts, workspaces/core/src/popover/Popover.tsx, workspaces/core/src/popover/private/types/GroupProps.ts
=> fix: MenuItem and Popover accessibility [MDS-604]

next-docs/pages/components/insetNativeSelect.tsx, next-docs/public/examples/avatar/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/group/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/insetNativeSelect/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/searchCmdk/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/avatar/Avatar.tsx, workspaces/core/src/avatar/styles/StatusDeprecated.tsx, workspaces/core/src/avatar/styles/Wrapper.tsx, workspaces/core/src/group/Group.tsx, workspaces/core/src/insetNativeSelect/InsetNativeSelect.tsx, workspaces/core/src/insetNativeSelect/private/types/InsetNativeSelectProps.ts, workspaces/core/src/insetNativeSelect/private/types/WithChildren.ts, workspaces/core/src/searchCmdk/SearchCmdk.tsx
=> fix: dark theme issues on Avatar, SearchCmdk, and InsetNativeSelect [MDS-600]

next-docs/components/themes/useThemes.tsx, next-docs/styles/themes.css, workspaces/themes/src/index.ts, workspaces/themes/src/tradeartMiniBetting.css
=> feat: add Tradeart Mini Betting theme [MDS-619]

next-docs/public/examples/tooltip/NotPortal.tsx, next-docs/public/examples/tooltip/__tests__/__snapshots__/index.test.tsx.snap
=> fix: Tooltip out of portal exampl

packages/assets/src/icons/IconLivespins.tsx, workspaces/base/package.json, workspaces/base/tsconfig.cjs.json, workspaces/base/tsconfig.esm.json
=> chore: commonjs cleanup

next-docs/public/examples/bottomSheet/__tests__/__snapshots__/index.test.tsx.snap, next-docs/utils/useComponent.ts
=> fix: live code examples [MDS-634]

next-docs/components/search/utils/getActions.ts, packages/assets/src/icons/IconLivespins.tsx
=> fix: search navigation [MDS-647]

workspaces/themes/src/sportsbet.css
https://www.figma.com/file/FuPXIU6dVQXIm7zas5ZBnG/Sportsbet---Theme?type=design&node-id=1016-325&mode=design&t=RmC0gwY7yt0u1ZbL-0
=> Update hit color on sb light theme

next-docs/components/getComponent.ts, next-docs/components/search/RenderResults.tsx, next-docs/components/search/utils/getActions.ts, next-docs/components/sidebar/Sidebar.tsx, next-docs/components/sidebar/navigation.tsx
=> fix: site search [MDS-651]

next-docs/tailwind.config.js
=> fix: search cmdk

next-docs/public/examples/combobox/Default.tsx, next-docs/public/examples/combobox/InsetMultiSelect.tsx, next-docs/public/examples/combobox/InsetSelect.tsx, next-docs/public/examples/combobox/InsetSelectStates.tsx, next-docs/public/examples/combobox/MultiSelect.tsx, next-docs/public/examples/combobox/Select.tsx, next-docs/public/examples/combobox/SelectStates.tsx, next-docs/public/examples/combobox/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/transformIcon/IconPreview.tsx
=> fix: update icons imports for Combobox [MDS-668]

next-docs/components/themes/useThemes.tsx, next-docs/styles/themes.css, workspaces/themes/src/index.ts, workspaces/themes/src/pay.css
=> feat: add pay.io theme [MDS-670]

next-docs/pages/components/circularProgress.tsx, next-docs/public/examples/circularProgress/Colors.tsx, next-docs/public/examples/circularProgress/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/circularProgress/CircularProgress.tsx, workspaces/core/src/circularProgress/private/types/Props.ts, workspaces/core/src/circularProgress/private/utils/getSize.ts
=> feat: remove color props from CircularProgress [MDS-521]

next-docs/pages/components/button.tsx, next-docs/public/examples/button/Multiline.tsx, next-docs/public/examples/button/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/button/__tests__/index.test.tsx
=> feat: add multiline Button example [MDS-624]

next-docs/public/examples/pagination/WithHref.tsx, next-docs/public/examples/pagination/__tests__/__snapshots__/index.test.tsx.snap
=> fix: add link to buttons on Pagination with hrefs [MDS-673]

workspaces/themes/src/partners.css
=> fix: update piccolo in partners.io theme [MDS-681] 

workspaces/tables/src/components/TD.tsx
=> Fixed: hidden data is visible when table row is selected or hovered

next-docs/pages/components/table.tsx, next-docs/public/examples/table/LongData.tsx, next-docs/public/examples/table/__tests__/index.test.tsx, workspaces/tables/src/components/BodyTR.tsx, workspaces/tables/src/components/TD.tsx, workspaces/tables/src/components/Table.tsx, workspaces/tables/src/private/types/BodyTRProps.ts, workspaces/tables/src/private/types/ClipProps.ts, workspaces/tables/src/private/types/RenderRowsProps.ts, workspaces/tables/src/private/types/TDProps.ts, workspaces/tables/src/private/types/TableProps.ts, workspaces/tables/src/private/utils/renderRows.tsx
=> Fixed: long data is visible in other cells of the table

next-docs/public/examples/table/LongData.tsx, next-docs/public/examples/table/__tests__/index.test.tsx
1. Corrected: an opportunity to expand any table column as much as possible.
2. FIxed:  a mistyping at table tests. Tests have been updated.
=> Fixed: provide an opportunity to expand any table column as much as possible

workspaces/core/src/bottomSheet/BottomSheet.tsx, workspaces/core/src/bottomSheet/private/utils/useDrag.ts
=> fix: BottomSheet closing behaviour [MDS-308]

next-docs/pages/components/combobox.tsx, next-docs/public/examples/combobox/VisualMultiSelect.tsx, next-docs/public/examples/combobox/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/combobox/__tests__/index.test.tsx, workspaces/core/src/combobox/Combobox.tsx, workspaces/core/src/combobox/private/types/ComboboxRootProps.ts, workspaces/core/src/combobox/private/types/ComboboxState.ts, workspaces/core/src/combobox/private/types/VisualMultiSelectProps.ts
=> MDS-707 Combobox Multiselect 

next-docs/components/codePreview/Preview.tsx, next-docs/pages/components/bottomSheet.tsx, next-docs/public/examples/bottomSheet/RootPortal.tsx, next-docs/public/examples/bottomSheet/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/bottomSheet/__tests__/index.test.tsx, workspaces/core/src/backdrop/Backdrop.tsx, workspaces/core/src/bottomSheet/BottomSheet.tsx, workspaces/core/src/bottomSheet/private/types/BottomSheetRootProps.ts
=> add custom root element support for bottomSheet

next-docs/pages/components/table.tsx, next-docs/public/examples/table/ExpandableCheckboxes.tsx, next-docs/public/examples/table/ExpandedWithModals.tsx, next-docs/public/examples/table/LongData.tsx, next-docs/public/examples/table/SelectableCheckboxes.tsx, next-docs/public/examples/table/__tests__/index.test.tsx, workspaces/tables/src/components/BodyTR.tsx, workspaces/tables/src/components/TH.tsx, workspaces/tables/src/components/Table.tsx, workspaces/tables/src/private/types/RenderRowsProps.ts, workspaces/tables/src/private/types/THProps.ts, workspaces/tables/src/private/utils/renderRows.tsx
=> MDS-738 Table & Checkbox Integration

next-docs/pages/components/combobox.tsx, next-docs/public/examples/combobox/LongNameOptions.tsx, next-docs/public/examples/combobox/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/combobox/__tests__/index.test.tsx
=> feat: examples of alignment of list controls

next-docs/public/examples/table/CustomContent.tsx, next-docs/public/examples/table/DeepTable.tsx, next-docs/public/examples/table/ExpandableCheckboxes.tsx, next-docs/public/examples/table/ExpandedRows.tsx, next-docs/public/examples/table/ExpandedWithModals.tsx
=> MDS-761: icons for expandable table rows have been replaced 

docs/app/components/server/chip/description.md, docs/app/components/server/chip/examples/Default.tsx, docs/app/components/server/chip/page.tsx, docs/app/components/types.ts, workspaces/base/src/chip/Chip.tsx
=> fix: add Chip to Docs, align colours [MDS-720]

docs/app/components/server/loader/description.md, docs/app/components/server/loader/examples/Default.tsx, docs/app/components/server/loader/page.tsx, docs/app/components/types.ts
=> fix: add Loader to Docs, align colours [MDS-722]

docs/app/components/server/pagination/description.md, docs/app/components/server/pagination/examples/Default.tsx, docs/app/components/server/pagination/page.tsx, docs/app/components/types.ts, workspaces/base/src/pagination/Pagination.tsx
=> fix: add Pagination to Docs, align colours [MDS-724]

next-docs/public/examples/table/ExpandableCheckboxes.tsx, workspaces/tables/src/components/Table.tsx
=> fix: mistakable selection of checkboxes with similar indexes

next-docs/pages/components/popover.tsx, next-docs/public/examples/popover/TooltipViewOpen.tsx, next-docs/public/examples/popover/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/popover/__tests__/index.test.tsx, workspaces/core/src/popover/Popover.tsx, workspaces/core/src/popover/private/types/PanelProps.ts
=> Add new example for popover

next-docs/pages/components/accordion.tsx, next-docs/public/examples/accordion/Background.tsx, next-docs/public/examples/accordion/ContentHeader.tsx, next-docs/public/examples/accordion/__tests__/__snapshots__/index.test.tsx.snap
=> remove ContentOutside component from documentation [MDS-784]

workspaces/core/src/dropdown/Dropdown.tsx
=> fix: dropdown shared states in form component [MDS-793]

next-docs/public/examples/form/WithInsetInput.tsx, next-docs/public/examples/form/__tests__/__snapshots__/index.test.tsx.snap
=> fix: Form border radius issue [MDS-794]

workspaces/tables/src/components/Table.tsx
=> fix: table isAllRowsExpanded 

workspaces/core/src/bottomSheet/BottomSheet.tsx, workspaces/core/src/bottomSheet/private/types/BottomSheetRootProps.ts
=> fix: bottomSheet default focus issue

next-docs/public/examples/table/ExpandedWithKeepState.tsx
=> fix: table selection optimisation

next-docs/public/transformIcon/IconPreview.tsx, next-docs/utils/useFilteredRequestQuery.ts
=> fix: DOM text reinterpreted as HTML scanning alert

next-docs/pages/components/progress.tsx, next-docs/public/examples/progress/WithLabels.tsx, next-docs/public/examples/progress/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/progress/__tests__/index.test.tsx, workspaces/core/src/progress/Progress.tsx, workspaces/core/src/progress/private/utils/getPinStyle.ts
=> fix: Progress styles and add Labels variant to docs [MDS-809]

next-docs/public/examples/table/ExtraLongDataView.tsx
=> fix: hydration error at the ExtraLong Table Data view example

next-docs/public/examples/table/DeepTable.tsx
=> fix: Expanded Rows with deep nesting example

next-docs/public/examples/table/MiniMap.tsx, workspaces/tables/src/components/Minimap.tsx
=> fix: Minimap example

next-docs/pages/components/popover.tsx, next-docs/public/examples/popover/AutoPositionDisable.tsx, next-docs/public/examples/popover/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/popover/__tests__/index.test.tsx, pnpm-lock.yaml, workspaces/core/src/popover/Popover.tsx, workspaces/core/src/popover/private/types/PopoverRootProps.ts
=> feat: add autoPositionDisable prop [MDS-839]

next-docs/pages/components/tabs.tsx, next-docs/public/examples/tabs/SelectedIndex.tsx, next-docs/public/examples/tabs/SelectedIndexSegment.tsx
=> Tabs - Selected example

workspaces/core/src/button/Button.tsx, workspaces/core/src/button/styles/Hover.tsx
=> chore: button cleanup

workspaces/core/src/private/presets/ds-moon-preset.js
=> fix: return button classnames to ds-moon-preset [MDS-847]

next-docs/public/examples/switch/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/switch/Switch.tsx
=> fix: remove z-indices from Switch [MDS-848]

workspaces/core/src/breadcrumb/Breadcrumb.tsx, workspaces/core/src/breadcrumb/private/types/Props.ts, workspaces/core/src/label/Label.tsx
=> feat: Allow configuring Breadcrumbs that when should it collapse

next-docs/public/examples/form/__tests__/__snapshots__/index.test.tsx.snap, next-docs/public/examples/textarea/__tests__/__snapshots__/index.test.tsx.snap, workspaces/core/src/textarea/Textarea.tsx
=> fix: Textarea disabled and read-only borders [MDS-792]

next-docs/public/examples/table/Zebra.tsx, workspaces/tables/src/components/TH.tsx, workspaces/tables/src/components/Table.tsx, workspaces/tables/src/private/types/THProps.ts
=> MDS-969 Fix Table sorting & zebra

workspaces/tables/src/components/Table.tsx, workspaces/tables/src/private/types/TableProps.ts
=> fix: add classname support to Table [MDS-982]

workspaces/cmdk/src/searchCmdk/SearchCmdk.tsx
=> fix: add classname support to SearchCmdk.Trigger [MDS-980]

workspaces/core/src/modal/Modal.tsx
=> fix: MDS-989 add initialFocus to Modal

.changeset/config.json, package.json, packages/components/CHANGELOG.md, packages/components/package.json, pnpm-lock.yaml
=> chore: fix disableFocusLock in Dialog

packages/themes/src/bitcasinoDark/bitcasinoDark.ts, packages/themes/src/bitcasinoLight/bitcasinoLight.ts
https://coingaming.atlassian.net/browse/CS-5656
=> feat: new bitcasino colours [CS-5656]

next-docs/CHANGELOG.md, next-docs/package.json, packages/themes/CHANGELOG.md, packages/themes/package.json, pnpm-lock.yaml
=> chore: bump moon-themes to v10.7.2

next-docs/CHANGELOG.md, next-docs/package.json, packages/themes/CHANGELOG.md, packages/themes/package.json, packages/themes/src/bitcasinoDark/bitcasinoDark.ts, packages/themes/src/bitcasinoLight/bitcasinoLight.ts, pnpm-lock.yaml
=> Deploy 10.13.5

docs/package.json, next-docs/package.json, package.json, packages/accordion/package.json, packages/assets/package.json, packages/calendar/package.json, packages/charts/package.json, packages/components/package.json, packages/core/package.json, packages/datepicker/package.json, packages/draggabletable/package.json, packages/fonts/package.json, packages/global/package.json, packages/icons/package.json, packages/notifications/package.json, packages/pagination/package.json, packages/popover/package.json, packages/select/package.json, packages/sidebar/package.json, packages/table/package.json, packages/themes/package.json, packages/utils/package.json, workspaces/tables/package.json
=> feat: update license to GPL
